# Generated by Django 4.2.7 on 2023-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stoke',
            field=models.IntegerField(),
        ),
    ]
